backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "base_de_datos"
    label: "🗄️ Base de Datos"
    files:
      - label: "📚 Proyectos"
        name: "proyectos"
        file: "datos_proyectos.json"
        fields:
          - label: "Lista de Obras"
            name: "obras"
            widget: "list"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Tipo", name: "tipo", widget: "select", options: ["Manhwa", "Manga", "Manhua", "Novela", "Animación"] }
              - { label: "Portada", name: "portada", widget: "image", required: false }
              
      - label: "📄 Capítulos"
        name: "capitulos"
        file: "datos_capitulos.json"
        fields:
          - label: "Lista de Capítulos"
            name: "lista"
            widget: "list"
            fields:
              - { label: "Obra", name: "obra", widget: "string" }
              - { label: "Número", name: "numero", widget: "number", value_type: "int" }
              - { label: "Archivo ZIP", name: "archivo_zip", widget: "file", required: false }